### ISSUE TITLE
Listado de posts

### ISSUE THREAD

**Issue by MireGM** [organizacion-sesion-3-MireiaGilMolla/plantilla-jekyll#1]
Con el nuevo layaout plantillabog, no obtengo el listado de posts de la carpeta posts.

 @pedroprieto

**Comment by pedroprieto** [comment]
Vale, ya está claro: el nombre de los ficheros de los posts no se adapta al formato requerido (te falta la fecha):
https://jekyllrb.com/docs/posts/#creating-posts

Cambia el nombre a los ficheros y verás que ya aparecen.

Un saludo!!
